### ISSUE TITLE
Update bmt-lite version

### ISSUE THREAD

**Issue by sarah-seitanakis** [ranking-agent/robokop-ara#37]
Update bmt-lite version in requirements.txt

**Comment by sarah-seitanakis** [comment]
[bmt-lite repo link](https://github.com/TranslatorSRI/bmt-lite)

**Comment by davefol** [comment]
Every bmt-lite release is characterized by two versions:
- bio link model version
- bmt-lite release version

Choosing a release amounts to picking a bio link model version then selecting the latest bmt-lite release for that version. At this time the options for biolnk model version are:
- 1.7.0
- 1.8.0
- 1.8.1
- 1.8.2
- 2.0.0
- 2.0.1
- 2.0.2
- 2.1.0
- 2.2.0
- 2.2.1
- 2.2.2
- 2.2.3
- 2.2.4
- 2.2.5

I'll be adding a PR that closes this issue by upgrading to the latest bmt-lite with the latest bio link version
```
-bmt-lite-1.8.2==1.0.2
+bmt-lite-2.2.5==2.2.0
```
